import { Box, Flex, HStack, Stack, Text } from '@chakra-ui/react';
import Head from 'next/head';
import { ReactNode } from 'react';
import Link from 'next/link';
import { Connect } from './Connect';
import { useRouter } from 'next/router';

type Props = {
  children?: ReactNode;
  title?: string;
};

const Layout = ({ children, title = 'Automatism art' }: Props) => {
  const router = useRouter();
  return (
    <Box>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        w="full"
        h={{ base: '100%', xl: '100vh' }}
        bg="black"
        color="white"
        direction={{ base: 'column', xl: 'row' }}
      >
        <Stack
          p="24px"
          maxW={{ base: '100%', xl: '400px' }}
          w="full"
          h="full"
          borderRight={{ base: 'none', xl: '1px solid #333333' }}
          gap="18px"
          position="relative"
          overflowY={{ xl: 'scroll' }}
          pb="40px"
        >
          <Text fontSize="5xl" fontWeight="semibold">
            Automatism
          </Text>
          <Link
            style={{ marginTop: '0px' }}
            target="_blank"
            href="https://twitter.com/davidhurley87"
          >
            <Text display="inline" color="blue.500">
              by hurls
            </Text>
          </Link>
          <Stack
            gap="12px"
            fontSize={{ base: '18px', xl: '21px' }}
            maxW="700px"
          >
            <Text>
              Automatism in art refers to a technique used by artists to access
              the subconscious mind in order to produce spontaneous,
              unpremeditated creations.
            </Text>
            <Text>
              The aim is to bypass the rational mind and access the{' '}
              {"artist's "}
              deeper, instinctual impulses, which can produce unexpected and
              often surprising results.
            </Text>
            <Text>
              Mint your NFT and join our community using AI to create and sell
              art.
            </Text>
          </Stack>
        </Stack>
        <Box w="full" p="24px" position="relative" overflowY="scroll">
          <HStack w="full" justify="space-between" pb="24px">
            <Flex gap="8" fontSize="21px">
              <Link href="/">
                <Text opacity={router.asPath === '/' ? '1' : '0.6'}>Art</Text>
              </Link>
              <Link href="/traits">
                <Text opacity={router.asPath === '/traits' ? '1' : '0.6'}>
                  Traits
                </Text>
              </Link>
              <Link href="/utility">
                <Text opacity={router.asPath === '/utility' ? '1' : '0.6'}>
                  Utility
                </Text>
              </Link>
            </Flex>
            <Box display={{ base: 'none', xl: 'block' }}>
              <Connect />
            </Box>
          </HStack>
          <Box>{children}</Box>
        </Box>
      </Flex>
    </Box>
  );
};

export default Layout;
