import { Box, Flex, HStack, Stack, Text } from '@chakra-ui/react';
import Head from 'next/head';
import { ReactNode } from 'react';
import Link from 'next/link';
import { Connect } from './Connect';
import { useRouter } from 'next/router';

type Props = {
  children?: ReactNode;
  title?: string;
};

const Layout = ({ children, title = 'Automatism art' }: Props) => {
  const router = useRouter();
  return (
    <Box>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w="full" h="100vh" bg="black" color="white">
        <Stack
          p="24px"
          maxW="444px"
          w="full"
          h="full"
          borderRight="1px solid #333333"
          gap="18px"
          position="relative"
          overflowY="scroll"
          pb="40px"
        >
          <Text fontSize="5xl" fontWeight="semibold">
            Automatism
          </Text>
          <Text style={{ marginTop: '0px' }}>by hurls</Text>
          <Stack gap="12px" fontSize="21px">
            <Text>
              Automatism in art refers to a technique used by artists to access
              the subconscious mind in order to produce spontaneous,
              unpremeditated creations.
            </Text>
            <Text>
              The aim is to bypass the rational mind and access the{' '}
              {"artist's "}
              deeper, instinctual impulses, which can produce unexpected and
              often surprising results.
            </Text>
            <Text>
              Mint your NFT and join our community using AI to create and sell
              art.
            </Text>
          </Stack>
        </Stack>
        <Box w="full" p="24px" position="relative" overflowY="scroll">
          <HStack w="full" justify="space-between" pb="24px">
            <Flex gap="8" fontSize="21px">
              <Link href="/">
                <Text opacity={router.asPath === '/' ? '1' : '0.6'}>Art</Text>
              </Link>
              <Link href="/traits">
                <Text opacity={router.asPath === '/traits' ? '1' : '0.6'}>
                  Traits
                </Text>
              </Link>
              <Link href="/utility">
                <Text opacity={router.asPath === '/utility' ? '1' : '0.6'}>
                  Utility
                </Text>
              </Link>
            </Flex>
            <Connect />
          </HStack>
          <Box>{children}</Box>
        </Box>
      </Flex>
    </Box>
  );
};

export default Layout;
